import { Client, Account, TablesDB, ID, Query, Permission, Role, Functions } from "https://cdn.jsdelivr.net/npm/appwrite@latest/+esm";
const ENDPOINT="https://nyc.cloud.appwrite.io/v1",PROJECT_ID="6aa6f346003cb3186f6e",DATABASE_ID="motogasto";const T={motos:"motos",produtos:"produtos",lancamentos:"lancamentos"};
const client=new Client().setEndpoint(ENDPOINT).setProject(PROJECT_ID);const account=new Account(client),db=new TablesDB(client),functions=new Functions(client);let user=null,motos=[],products=[];const $=s=>document.querySelector(s),plateNorm=p=>(p||"").toUpperCase().replace(/[^A-Z0-9]/g,""),todayISO=()=>new Date().toISOString().slice(0,10),money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
async function list(t,q=[]){let r=await db.listRows({databaseId:DATABASE_ID,tableId:t,queries:[Query.equal("userId",user.$id),...q]});return r.rows||[]}
async function refresh(){[motos,products]=await Promise.all([list(T.motos),list(T.produtos)]);render();}
function render(){$('#motosList').innerHTML=motos.map(m=>`<div class="item"><b>${m.placa}</b> — ${m.modelo||''} ${m.cor||''}</div>`).join('')||'Nenhuma moto.';$('#productsList').innerHTML=products.map(p=>`<div class="item"><b>${p.nome}</b> <span class="badge">${p.tipo}</span><br>${money(p.valor)} <span class="muted">${p.apelidos||''}</span></div>`).join('')||'Nenhum produto.';$('#manualProduct').innerHTML='<option value="">Selecione...</option>'+products.map(p=>`<option value="${p.$id}">${p.nome} — ${money(p.valor)}</option>`).join('')}
async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#who').textContent=user.email;await refresh()}function showLogin(){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden')}
$('#loginBtn').onclick=async()=>{try{await account.createEmailPasswordSession({email:$('#email').value,password:$('#password').value});user=await account.get();showApp()}catch(e){$('#loginMsg').textContent=e.message}};$('#signupBtn').onclick=async()=>{try{await account.create({userId:ID.unique(),email:$('#email').value,password:$('#password').value});$('#loginBtn').click()}catch(e){$('#loginMsg').textContent=e.message}};$('#logoutBtn').onclick=async()=>{await account.deleteSession({sessionId:'current'});showLogin()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.section').forEach(s=>s.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='relatorios')loadReport()});
$('#saveMotoBtn').onclick=async()=>{let placa=plateNorm($('#motoPlate').value);if(!placa)return alert('Digite a placa');await db.createRow({databaseId:DATABASE_ID,tableId:T.motos,rowId:ID.unique(),data:{userId:user.$id,placa,modelo:$('#motoModel').value,cor:$('#motoColor').value,observacao:$('#motoObs').value},permissions:[Permission.read(Role.user(user.$id)),Permission.update(Role.user(user.$id)),Permission.delete(Role.user(user.$id))]});await refresh();alert('Moto salva')};
$('#saveProdBtn').onclick=async()=>{let nome=$('#prodName').value.trim(),valor=Number($('#prodPrice').value);if(!nome||isNaN(valor))return alert('Informe nome e valor');await db.createRow({databaseId:DATABASE_ID,tableId:T.produtos,rowId:ID.unique(),data:{userId:user.$id,nome,tipo:$('#prodType').value,valor,apelidos:$('#prodAliases').value},permissions:[Permission.read(Role.user(user.$id)),Permission.update(Role.user(user.$id)),Permission.delete(Role.user(user.$id))]});await refresh();alert('Produto salvo')};
async function saveLaunch(placa,itens,origem='manual',texto=''){let total=itens.reduce((s,i)=>s+Number(i.subtotal),0);await db.createRow({databaseId:DATABASE_ID,tableId:T.lancamentos,rowId:ID.unique(),data:{userId:user.$id,placa,data:todayISO(),itensJson:JSON.stringify(itens),total,origem,textoOriginal:texto},permissions:[Permission.read(Role.user(user.$id)),Permission.update(Role.user(user.$id)),Permission.delete(Role.user(user.$id))]})}
$('#manualAddBtn').onclick=async()=>{let placa=plateNorm($('#manualPlate').value),p=products.find(x=>x.$id===$('#manualProduct').value),q=Number($('#manualQty').value||1);if(!motos.some(m=>m.placa===placa))return alert('Placa não cadastrada');if(!p)return alert('Selecione um produto');await saveLaunch(placa,[{productId:p.$id,nome:p.nome,quantidade:q,valorUnitario:Number(p.valor),subtotal:q*Number(p.valor)}]);alert('Lançamento salvo')};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){let r=new SR();r.lang='pt-BR';r.onresult=e=>$('#spokenText').value=e.results[0][0].transcript;r.onend=()=>$('#micBtn').textContent='🎙️ Falar novamente';$('#micBtn').onclick=()=>{r.start();$('#micBtn').textContent='🎙️ Ouvindo...'}}else $('#micBtn').onclick=()=>alert('Use Chrome/Edge em HTTPS ou localhost para voz.');
function localInterpret(text){let flat=text.toUpperCase().replace(/[^A-Z0-9]/g,''),placa=(motos.find(m=>flat.includes(m.placa))||{}).placa||null,itens=[];for(let p of products){let terms=[p.nome,...(p.apelidos||'').split(',')].map(x=>x.trim()).filter(Boolean);if(terms.some(t=>text.toUpperCase().includes(t.toUpperCase())))itens.push({productId:p.$id,nome:p.nome,quantidade:1,valorUnitario:Number(p.valor),subtotal:Number(p.valor)})}return{plate:placa,items:itens,warnings:['Modo de segurança local: confira quantidades.']}}
$('#interpretBtn').onclick=async()=>{let text=$('#spokenText').value.trim();if(!text)return;let data;try{let ex=await functions.createExecution({functionId:'interpretar-voz',body:JSON.stringify({text}),async:false});data=JSON.parse(ex.responseBody||'{}')}catch(e){data=localInterpret(text)}let placa=plateNorm(data.plate||''),itens=(data.items||[]).map(i=>{let p=products.find(x=>x.$id===i.productId)||products.find(x=>x.nome.toLowerCase()===(i.nome||'').toLowerCase());if(!p)return null;let q=Number(i.quantidade||1);return{productId:p.$id,nome:p.nome,quantidade:q,valorUnitario:Number(p.valor),subtotal:q*Number(p.valor)}}).filter(Boolean);let valid=motos.some(m=>m.placa===placa);$('#interpretResult').innerHTML=`<div class="${valid&&itens.length?'ok':'warn'}"><b>Placa:</b> ${placa||'não identificada'}<br>${itens.map(i=>`${i.quantidade}x ${i.nome} — ${money(i.subtotal)}`).join('<br>')}<br><b>Total: ${money(itens.reduce((s,i)=>s+i.subtotal,0))}</b></div>`+(valid&&itens.length?'<button id="confirmAI" class="success">Confirmar e salvar</button>':'');if($('#confirmAI'))$('#confirmAI').onclick=async()=>{await saveLaunch(placa,itens,'ia',text);alert('Salvo com sucesso')}};
async function rows(date,placa=''){let q=[Query.equal('data',date)];if(placa)q.push(Query.equal('placa',plateNorm(placa)));return list(T.lancamentos,q)}function showRows(r,el){let total=0;el.innerHTML=r.map(x=>{total+=Number(x.total);let it=JSON.parse(x.itensJson||'[]');return `<div class="item"><b>${x.placa}</b> — ${money(x.total)}<br>${it.map(i=>`${i.quantidade}x ${i.nome}`).join(', ')}</div>`}).join('')+`<div class="big">Total: ${money(total)}</div>`}
$('#todayBtn').onclick=async()=>showRows(await rows(todayISO(),$('#searchPlate').value),$('#todayResult'));async function loadReport(){let r=await rows($('#reportDate').value||todayISO());window._rows=r;showRows(r,$('#reportResult'))}$('#loadReportBtn').onclick=loadReport;$('#exportBtn').onclick=()=>{let csv='Data;Placa;Itens;Total\n';for(let r of (window._rows||[]))csv+=`${r.data};${r.placa};"${JSON.parse(r.itensJson||'[]').map(i=>`${i.quantidade}x ${i.nome}`).join(', ')}";${Number(r.total).toFixed(2).replace('.',',')}\n`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='motogasto.csv';a.click()};$('#reportDate').value=todayISO();try{user=await account.get();showApp()}catch{showLogin()}
